### ISSUE TITLE
possibly broken in Firefox 38

### ISSUE THREAD

**Issue by slumbergod** [edawn/selected-search-firefox-addon#1]
I usually have middle click to open the link in the current tab. From FF38.01 it has stopped working.

**Comment by edawn** [comment]
fixed in current version

**Comment by slumbergod** [comment]
I updated to the latest version but now SS is not working at all. I can't even get a pop-up. It could be related to my Firefox install. I have noticed some strange behaviours in this new version. If it works for everyone else I'd appreciate someone telling me so I can look for the cause of my issues.

**Comment by edawn** [comment]
i just tried with a new/blank profile. everything seems to be working fine. did you get the update from AMO?

**Comment by slumbergod** [comment]
Hi, I think it may be time for me to start with a new profile too. If I get
time I'll try it today. The transition to FF38 hasn't been quite as smooth
so my profile is probably corrupted. I'll let you know if it sorts my
problem. Thanks!

**Comment by slumbergod** [comment]
Yip, it was my profile. SS is working again as it should. I am sorry if I
created work for you for nothing. Your efforts are appreciated!

On 21 May 2015 at 10:19, David Scott slumbergod@gmail.com wrote:

> Hi, I think it may be time for me to start with a new profile too. If I
> get time I'll try it today. The transition to FF38 hasn't been quite as
> smooth so my profile is probably corrupted. I'll let you know if it sorts
> my problem. Thanks!
> On 21/05/2015 9:01 am, "edawn" notifications@github.com wrote:
> 
> > i just tried with a new/blank profile. everything seems to be working
> > fine. did you get the update from AMO?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/edawn/selected-search-firefox-addon/issues/1#issuecomment-104037376
> > .

## 

_David Scott_, BSc BA
_Administration, myBJJ New Zealand http://www.mybjj.co.nz_
