### ISSUE TITLE
Copying selection to clipboard via button

### ISSUE THREAD

**Issue by Gitoffthelawn** [edawn/selected-search-firefox-addon#3]
Great extension.  Thanks!

Can you add a button before/after the search engines that will copy the selection to the clipboard?

(The extension has an option to automatically copy the selection to the clipboard each time there is a selection, but this can overwrite data in the clipboard.)

**Comment by edawn** [comment]
Due to the very uncertain future of the Firefox Add-on development, I probably won't invest any more time in creating new features.
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
It's a bit sad, cause who needs another chrome?

**Comment by Gitoffthelawn** [comment]
I agree that we don't need another Chrome.  But hopefully Mozilla will add so many custom features to Web Extensions that Firefox will retain it's power.

Also, Mozilla knows that one of the strongest assets is their add-on ecosystem.  I wouldn't be surprised if they delay removal of XUL for quite some time.
